// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrn7vJU8FmMuh1Jd8U2GSqzermsGDM63Q',
    appId: '1:748001391660:android:f702ecb45b1515b4e14d89',
    messagingSenderId: '748001391660',
    projectId: 'chatgpt-2e83e',
    storageBucket: 'chatgpt-2e83e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8jN9S9XgKons8qUzR0KNVf3mN8cTgiac',
    appId: '1:748001391660:ios:2a2183fdc85e8b32e14d89',
    messagingSenderId: '748001391660',
    projectId: 'chatgpt-2e83e',
    storageBucket: 'chatgpt-2e83e.appspot.com',
    androidClientId: '748001391660-0e5ce8kmv50ga60qku5g1jq1738cncsb.apps.googleusercontent.com',
    iosClientId: '748001391660-4af9dhkici0h3o7uo0ti24eq5torludf.apps.googleusercontent.com',
    iosBundleId: 'ai.chadster.mobile',
  );
}
